[invite]
# 需要刷邀请量的放邀请码到这即可，这里对应的钱包没有安全风险，可以在服务端运行
codes = ['xyh76m', '6ngtba', 'ea6m5z']
# 每个邀请码每天邀请的数量
count = 5
[wallet]
# 助记词 12 或 24 个单词，确保是在本地或可信的终端运行，避免使用有资产的钱包
mnemonic = "word..."
# 子钱包数量
count = 20